version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  api:
    container_name: api
    build:
      dockerfile: ./docker/api.dockerfile
      context: .
      # Only will build development stage from our dockerfile
      # target: development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - pg_db
    networks:
      - app_net

  pg_db:
    build:
      context: .
      dockerfile: ./docker/postgres.dockerfile
      args:
        - PG_GROUP=${PG_GROUP:-1000}
        - PG_USER=${PG_USER:-1000}
    container_name: pg_db
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_db:/var/lib/postgresql/data
    networks:
      - app_net
